[atlanta]
webserver1 ansible_host=172.31.37.175

#[atlanta:vars]
#service_name=nginx


[bostan]
webserver2 ansible_host=172.31.41.98

[usservers:children]
atlanta
bostan


[usservers:vars]
service_name=apache2
#  
