- hosts: bostan
  remote_user: ubuntu
  become_user: root
  become_method: sudo
  become: yes
  vars:
    userlist:
      - testuser1
      - testuser2
  tasks:
    - name: creating testusers
      user: 
        name: "{{item}}"
      with_items: "{{userlist}}" 
    - name: creating prod users
      user: 
        name: "{{item}}"
      with_items:
          - produser1
          - produser2
          - produser3  
    - name: with-items
      debug:
        msg:"{{item}}"
      with_items: "{{userlist}}"  
    - name: prod list variables from inventory    
      debug:
        msg: "{{item}}"
      with_items: "{{prodlist}}"    
