- hosts: webserver
  remote_user: ubuntu
  become_user: root
  become_method: sudo
  become: yes
  tasks:
    - name: get current date details using register
      shell: date
      register: currdate
    - debug: msg="{{currdate.stdout}}"
    - name: get uptime
      shell: uptime
      register: updetails
    - debug: msg="{{updetails.stdout}}"     
