- name: check the MQ installation packages
  hosts: dbserver
  remote_user: ubuntu
  become_user: root
  become: yes
  vars:
    package: "httpd"
  tasks:
    - name: Gather the package facts
      package_facts:
        manager: auto
    - name: Check whether a {{ package }}  is installed
      ansible.builtin.debug:
        msg: "{{ package }} {{ ansible_facts.packages[ package ][0].version }} is installed!"
      when: "package in ansible_facts.packages"      
