- hosts: dbserver
  remote_user: ubuntu
  become_user: root
  become_method: sudo
  become: yes
  tasks:
    - name: create MQ directory
      file:
        path: /home/ubuntu/MQ
        state: directory
        owner: ubuntu
        group: ubuntu
        mode: 0777
    - name: check MQ instalaltion file exists on the path
      stat:
        path: "/home/ubuntu/MQ/IBM_MQ_9.0.0.0_LINUX_X86-64.tar.gz"
      register: file_data
    - name: report file exists or not 
      debug: 
        msg: "file not exists"
      when: not file_data.stat.exists
      notify: moveMQfile
    - name: extract tar file
      command: 'tar -xvf /home/ubuntu/MQ/IBM_MQ_9.0.0.0_LINUX_X86-64.tar.gz'
      register: extractdetails
        #- debug: msg="{{extractdetails.stdout}}"
    
  handlers:
      - name: moveMQfile
        copy:
          src: /home/ansible/.ansible/IBM_MQ_9.0.0.0_LINUX_X86-64.tar.gz
          dest: /home/ubuntu/MQ      
          owner: root
          mode: 0777          
