- hosts: dbserver
  remote_user: ubuntu
  become_user: root
  become_method: sudo
  become: yes
  tasks:
    - name: accept the licence
      command: '/home/ubuntu/MQServer/mqlicense.sh -accept -text_only'
      become_user: root
      become: yes
    - name: install MQ componenets
      command: 'rpm -ivh /home/ubuntu/MQServer/{{item}}'
      with_items:
       - MQSeriesJava-9.0.0-0.x86_64.rpm
       - MQSeriesJRE-9.0.0-0.x86_64.rpm  
       - MQSeriesRuntime-9.0.0-0.x86_64.rpm
       - MQSeriesServer-9.0.0-0.x86_64.rpm     
