- name : check the os family
  debug:
    msg: "{{ ansible_os_family}}"
- name: install httpd on "{{ansible_os_family}} "
  yum:
    name: "{{install.name}}"
    state: "{{install.state}}"
    update_cache: "{{install.update_cache}}"  
  when: ansible_os_family == "RedHat"
- name: start httpd on "{{ansible_os_family}} "
  service:
    name: "{{service.name}}"
    state: "{{service.state}}"
  when: ansible_os_family == "RedHat"

- name: copy the httml file
  copy:
    dest: /var/www/httml
    src: hellow.html 
  when: ansible_os_family == "RedHat"    
